FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g nodemon

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD sh -c "until nc -z db 3306; do echo 'Waiting for DB...'; sleep 2; done && npx prisma migrate deploy && npm run dev"